# Generated by Django 4.0.3 on 2022-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=350)),
                ('img', models.CharField(max_length=500)),
                ('current_date', models.DateField()),
                ('user', models.CharField(max_length=20)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
