# Generated by Django 4.0.3 on 2022-04-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0004_post_updated_at_alter_post_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
