# Generated by Django 4.0.3 on 2022-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0008_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
